version: '3.8'

services:
  app:
    build: .
    depends_on:
      - redis
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - red_local

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - red_local

networks:
  red_local:
    driver: bridge