services:
  app:
    build: .
    depends_on:
      - redis
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      - red_local

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - red_local
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  red_local:
    driver: bridge